name: live_coding
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1
  huawei_hmsavailability: ^6.12.0+300
  huawei_push: ^6.12.0+303
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.5

  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
   uses-material-design: true
